### ISSUE TITLE
Update to Angular 4

### ISSUE THREAD

**Issue by emilerousseau** [juristr/angular-testing-recipes#1]
New Angular is much improved. Consider updating guide. Recommend using angular-cli as this saves hastle during installation process and Rails-style generate commands can aid work-flow, particularly in rapid-deploy critical scenarios.

~Emile Rousseau xx

**Comment by juristr** [comment]
@emilerousseau Hi Emile, thanks for your suggestions.

Actually the repository is already generated with the Angular CLI and upgraded to Angular 4+. If you take a look at the [package.json](https://github.com/juristr/angular-testing-recipes/blob/master/package.json#L6) you see how the various script instructions get delegated to the Angular CLI underneath.

> New Angular is much improved

The repository should leverage the latest Angular 4+ version. Did you find any specific parts in the source code/tests which could be improved specifically due to newly introduced features in Angular 4? In case let me know or submit a PR, that'd be awesome :)

**Comment by emilerousseau** [comment]
My apologies. I was simply going off the _Angular2_ in the README.md, but I see now the following plus can be read as including Angular4. I have been trying my best to be more community active so I shall research your repository more thoroughly and see if I can make any more useful suggestions or pull requests. Thank you for taking the time out to give a full response.

**Comment by juristr** [comment]
No worries. I'll give the repo a closer look again in a couple of weeks. I produce a lot of content on [my blog](https://juristr.com/blog) and on [Egghead.io](https://egghead.io/instructors/juri-strumpflohner) and keeping all the stuff up-to-date is kinda tough :smile:. Therefore, any feedback more than welcome.

There's also the slides and recording of the talk: https://github.com/juristr/angular-testing-recipes#talk-video--slides
